### ISSUE TITLE
Make examples avaliable online

### ISSUE THREAD

**Issue by rpominov** [rpominov/react-demo#24]
Currently one needs to clone the repo and run examples locally in order to see them.
Would be cool if examples were available online somehow.

**Comment by Guria** [comment]
http://www.webpackbin.com/EymrSQ70x

**Comment by Guria** [comment]
But it also pretty easy to self-host on github pages as well :)

**Comment by rpominov** [comment]
Yeah, I was thinking about github pages, but I don't want to setup webpak/babel/etc. I use https://github.com/insin/react-heatpack which allows not to setup all this for development.

http://www.webpackbin.com/EymrSQ70x looks great. We should create a bin with our "official" example https://github.com/rpominov/react-demo/blob/master/examples/index.js

**Comment by Guria** [comment]
There is an issue with official example: P.callback is blocked due cross-origin issues :(

**Comment by rpominov** [comment]
Seems to work fine http://www.webpackbin.com/4J0Js5QAg , I didn't notice issues with P.callback

**Comment by rpominov** [comment]
Added the link to readme.
