### ISSUE TITLE
Error PropTypes update React v15.5.4

### ISSUE THREAD

**Issue by robbinjanssen** [rpominov/react-demo#40]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

In this version of React PropTypes is Deprecated, see: https://github.com/facebook/react/releases/tag/v15.5.4

**Comment by rpominov** [comment]
Hey, @robbinjanssen! Thanks you for the report. I don't have much time to work on this right now, but I would definitely merge a PR with the fix.

**Comment by robbinjanssen** [comment]
I'll see if I have time to fix this later this week. Have been looking at the source for a while and am a bit tempted to update more dependencies like `eslint-config-airbnb` etc, but that would take up a lot of time. Might be wise to just update `react` and `react-dom` for now ;-)

**Comment by rpominov** [comment]
Yea, other dependencies need update, but that a separate issue.

As far as I understand the tricky part here is to make react-demo work with both older and current versions of React somehow. I saw this thread on twitter, maybe it can be helpful https://twitter.com/kentcdodds/status/850492084700168192

**Comment by robbinjanssen** [comment]
What do you mean with 'older' versions of react? Why would updating react conflict with old versions? Not sure I understand

**Comment by rpominov** [comment]
I meant that the new version of react-demo that we'll release should work with both `react@15.5` and `react@15.4`.

Alternatively we could just release a new version that works only with `react@15.5` and newer, but that may cause problems for people who have to use older react versions but want to use latest react-demo (in case we add new features or fix a critical bug later).

Here is an example of a workaround that @kentcdodds did for glamorous: https://github.com/paypal/glamorous/pull/32 .
